version: "3.5"

networks:
  python_hello_network:
    driver: bridge
    name: python_hello_network
    ipam:
      driver: default

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - python_hello
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - python_hello_network

  python_hello:
    container_name: python_hello
    build:
      context: .
      dockerfile: Dockerfile.python
    expose:
      - 5000
    volumes:
      - ./app:/app
    networks:
      - python_hello_network
