version: "3.5"

networks:
  python_network:
    driver: bridge
    name: python_network
    ipam:
      driver: default

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    depends_on:
      - python
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - python_network

  python:
    container_name: python
    build:
      context: .
      dockerfile: Dockerfile.python
    expose:
      - 5000
    volumes:
      - ./app:/app
    networks:
      - python_network
